In [6]:
import numpy as np

# Matrix Operation and Linear Equation

In [7]:
# create a two square matrix
x = np.array([[1,5,6],[8,5,9],[1,0,3]])
z = np.array([[12,20,-3],[5,-8,5],[6,9,17]])

print(x,'\n')
print(z)

[[1 5 6]
 [8 5 9]
 [1 0 3]] 

[[12 20 -3]
 [ 5 -8  5]
 [ 6  9 17]]


In [8]:
# Add and subtraction matrices

added = x.__add__(z)
sub = x.__sub__(z)

print(added,'\n')
print(sub)

[[13 25  3]
 [13 -3 14]
 [ 7  9 20]] 

[[-11 -15   9]
 [  3  13   4]
 [ -5  -9 -14]]


In [9]:
# piecewise multiplication and multiplaction of two matrices


piecewise = x.__mul__(z)
mul = x.__matmul__(z)

print(piecewise,'\n')
print(mul)

[[ 12 100 -18]
 [ 40 -40  45]
 [  6   0  51]] 

[[ 73  34 124]
 [175 201 154]
 [ 30  47  48]]


In [11]:
# 1x+1y=2 and 10x+35y=30

A = np.array([[1,1],[10,35]])
b = np.array([[2],[30]])

# Verify the size of the vector A and b
print('dim. of matrix A = ',A.shape)
print('dim. of matrix b = ',b.shape)


dim. of matrix A =  (2, 2)
dim. of matrix b =  (2, 1)


In [12]:
# finding the determinant of a matrix

np.linalg.det(A)

25.000000000000007

In [13]:
# Finding the inverse of the matrix A

inv_A = np.linalg.inv(A)
print(inv_A)

[[ 1.4  -0.04]
 [-0.4   0.04]]


In [14]:
# finding the solution
sol = inv_A.dot(b)
print(sol)

[[1.6]
 [0.4]]


In [15]:
# check your solution
print(1*sol[0] + 1*sol[1])
print(10*sol[0] + 35*sol[1])

[2.]
[30.]


In [ ]:
# Solve the system
# 4x+2y+4z = 44
# 5x+3y+7z = 56
# 9x+3y+6z = 72

# Computing Eigenvalues and Eigenvectors

In [16]:
A = np.array([[4,0,1],[2,-2,3],[7,5,0]])
w, v = np.linalg.eig(A)
print("Eigenvalues:\n",w)
print("Eigenvectors:\n",v)

Eigenvalues:
 [ 6.          1.16227766 -5.16227766]
Eigenvectors:
 [[-0.40824829 -0.27425784 -0.08167547]
 [-0.40824829  0.56487359 -0.65827525]
 [-0.81649658  0.7782676   0.74833336]]
